### ISSUE TITLE
Can I use this on Vue.js ?

### ISSUE THREAD

**Issue by ksmark8543** [PButcher/flipdown#26]
Hi, I want to use flipdown on Vue.js.
But I still don't know how to set up on my project.
The error message is "FlipDown is not defined", I think it's actually flipdown doesn't export module...
How should I do?
Please help me! :)

**Comment by PButcher** [comment]
You should be able to add one of the following at the end of the `dist/flipdown.js` depending on your environment, that way Flipdown will be available as a module.

`module.exports = Flipdown` or `export default Flipdown`

Let me know how you get on.
