### ISSUE TITLE
Support Angular

### ISSUE THREAD

**Issue by MaxenceEpitech** [PButcher/flipdown#35]
Hello,

I'd like to know if there is any way that this code work with angular 10.
Did you have any idea on how I should implement it please ?

I have try to viewChild and assign Flipdown to it
```
@ViewChild('flipdown') flipdown: ElementRef;
```

And also _createClass from Flipdown.

**Comment by kaue-delmonte-0** [comment]
Hi MaxenceEpitech!

First you need to install FlipDown packages using `npm install flipdown --save`

Then declare FlipDown existence to your angular.json file:

```
{
    "projects": {
        "my-app": {
            "architect": {
                "build": {
                    "options": {
                        "styles": [
                            "src/styles.css",
                            "node_modules/flipdown/src/flipdown.css"
                        ],
                        "scripts": [
                            "node_modules/flipdown/src/flipdown.js"
                        ]
                    }
                }
            }
        }
    }
}
```
So you can declare a variable in your component and use FlipDown function:

```
import { AfterViewInit, Component } from '@angular/core';

declare var FlipDown: any;

@Component({
    selector: 'FlipDown',
    template: '<div id="flipdown", class="flipdown">'
})
export class FlipDownComponent implements AfterViewInit {

    ngAfterViewInit(): void {

        new FlipDown(1538137672).start();

    }

}
```

**Comment by PButcher** [comment]
As a solution has been posted and I do not currently plan to create an Angular version of this lib, I will close this. Thanks.
