### ISSUE TITLE
Tearing down the javascript

### ISSUE THREAD

**Issue by ykamin-booth** [PButcher/flipdown#40]
Hi, what's the best way to tear down a flipdown instance? I don't see a function that does so.

**Comment by PButcher** [comment]
For anyone looking for this in future, here's how you can do it.

```js
// Clear FlipDown's internal interval
clearInterval(flipdown.countdown);
// Remove all generated elements inside the FlipDown container
document.getElementById("flipdown").replaceChildren();
```

After doing this, you can construct a new instance of FlipDown.
