### ISSUE TITLE
Animation is out of sync in Safari

### ISSUE THREAD

**Issue by vasiliki-b** [PButcher/flipdown#8]
The numbers change before the flip animation completes.

You must add `-webkit-backface-visibility: hidden;` to your css for front and rear rotor leaves, because `backface-visibility` alone is not supported by ios/Safari.

**Comment by PButcher** [comment]
Thanks for spotting and cheers for the fix. Fixed in 12173d167fc27d30a36b017f2de4aa978551ff40

Added you to the acknowledgements.

**Comment by PButcher** [comment]
It seems fine to me? In which version of Safari are you seeing this behaviour?

**Comment by vasiliki-b** [comment]
Safari 12.0
